### ISSUE TITLE
Capture with result output

### ISSUE THREAD

**Issue by gamelaster** [chuckfairy/node-webcam#2]
Hey,

Is possible to get output in capture function callback? Actually I can do it with reading the JPG, but it is a really interesting way.

Thanks

**Comment by chuckfairy** [comment]
Thank you for the input. I like the idea. I think an addition to solve this, could be a param in the Webcam() creation options to specify a callback return type I.E { callbackReturn: "buffer" }. Since some use cases might not need a buffer / base64 string, defaulting to the current return of the capture callback, the location of the output file, will be the fastest.

I have pushed up some API to the Webcam class regarding this case. getShot(), getBase64(), getLastShot() will return a Buffer (or base64) of the image. This will lead to the callback return param like discussed above and I will close this once that is added.

https://github.com/chuckfairy/node-webcam/commit/87724bf843887b4dc50d4a3325a35e20748d034b

**Comment by GAMELASTER** [comment]
nice! Thanks :+1:

**Comment by chuckfairy** [comment]
`callbackReturn` option added to Webcam constructor. With options buffer, location, and base64.

https://github.com/chuckfairy/node-webcam#api-usage
